/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ScheduleGnome;

import java.io.IOException;
import java.util.ArrayList;

import com.opencsv.exceptions.CsvValidationException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        //new App().parseTest();
    }

    public void parseTest(){
        ArrayList<Course> courses = new ArrayList<Course>();
        ParseCourses parser = new ParseCourses();
        
        parser.readCourses(courses);
        
        for (Course course : courses) {
            System.out.println((Course)course);
        }
    }
}
