/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ScheduleGnome;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.lang.Object;
import java.util.PriorityQueue;

class MatchTest {
    @Test
    void filtersForDept() {
//        Search searchingTool = new Search();
//        searchingTool.setDept("COMP 314");
//        Course crs = new Course(0, "COMP 314 A", "FOUN COMP SCI", "FOUNDATIONS OF COMPUTER SCIENCE", LocalTime.parse("10:00:00"), LocalTime.parse("10:50:00"), x, "STEM", "326");
//        assertEquals(1, searchingTool.isMatch(crs));
    }
}
