/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ScheduleGnome;

// I thought this might have been autogenerated and wrote over the file then
// moved my stuff into a different file, so if you wrote an AppTest in here
// I am sorry - Heston
